/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountSelect: typeof import('./components/entry/AccountSelect.vue')['default']
    AmountText: typeof import('./components/common/AmountText.vue')['default']
    BaseChart: typeof import('./components/chart/BaseChart.vue')['default']
    BudgetCard: typeof import('./components/stats/BudgetCard.vue')['default']
    CategoryGrid: typeof import('./components/entry/CategoryGrid.vue')['default']
    CategoryIcon: typeof import('./components/common/CategoryIcon.vue')['default']
    CategoryRankList: typeof import('./components/stats/CategoryRankList.vue')['default']
    DateSelect: typeof import('./components/entry/DateSelect.vue')['default']
    EmptyState: typeof import('./components/common/EmptyState.vue')['default']
    FilterPopup: typeof import('./components/bills/FilterPopup.vue')['default']
    MonthSwitcher: typeof import('./components/common/MonthSwitcher.vue')['default']
    QuickEntryPanel: typeof import('./components/entry/QuickEntryPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TransactionEditSheet: typeof import('./components/bills/TransactionEditSheet.vue')['default']
    TransactionItem: typeof import('./components/bills/TransactionItem.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanNumberKeyboard: typeof import('vant/es')['NumberKeyboard']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanProgress: typeof import('vant/es')['Progress']
    VanSearch: typeof import('vant/es')['Search']
    VanSwipeCell: typeof import('vant/es')['SwipeCell']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTag: typeof import('vant/es')['Tag']
  }
}
